name: Code quality

on:
  push:
    branches:
      - main

jobs:
  code-quality:
    name: Code quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run go vet
        run: go vet ./...

      - name: Install goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Unit tests
        run: make test
